addons:
  apt:
    packages:
      - python-pygments

install:
  - rm -rf public || exit 0

script:
  - binaries/hugo

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master